/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TomorrowRouteImport } from './routes/tomorrow'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Next7DaysRouteImport } from './routes/next-7-days'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as TagNameRouteImport } from './routes/tag.$name'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as CalendarWeekRouteImport } from './routes/calendar.week'
import { Route as CalendarMonthRouteImport } from './routes/calendar.month'
import { Route as ProjectIdKanbanRouteImport } from './routes/project.$id.kanban'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TomorrowRoute = TomorrowRouteImport.update({
  id: '/tomorrow',
  path: '/tomorrow',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Next7DaysRoute = Next7DaysRouteImport.update({
  id: '/next-7-days',
  path: '/next-7-days',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagNameRoute = TagNameRouteImport.update({
  id: '/tag/$name',
  path: '/tag/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarWeekRoute = CalendarWeekRouteImport.update({
  id: '/calendar/week',
  path: '/calendar/week',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarMonthRoute = CalendarMonthRouteImport.update({
  id: '/calendar/month',
  path: '/calendar/month',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdKanbanRoute = ProjectIdKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/completed': typeof CompletedRoute
  '/inbox': typeof InboxRoute
  '/next-7-days': typeof Next7DaysRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tomorrow': typeof TomorrowRoute
  '/trash': typeof TrashRoute
  '/calendar/month': typeof CalendarMonthRoute
  '/calendar/week': typeof CalendarWeekRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/tag/$name': typeof TagNameRoute
  '/calendar/': typeof CalendarIndexRoute
  '/project/$id/kanban': typeof ProjectIdKanbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/completed': typeof CompletedRoute
  '/inbox': typeof InboxRoute
  '/next-7-days': typeof Next7DaysRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tomorrow': typeof TomorrowRoute
  '/trash': typeof TrashRoute
  '/calendar/month': typeof CalendarMonthRoute
  '/calendar/week': typeof CalendarWeekRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/tag/$name': typeof TagNameRoute
  '/calendar': typeof CalendarIndexRoute
  '/project/$id/kanban': typeof ProjectIdKanbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/completed': typeof CompletedRoute
  '/inbox': typeof InboxRoute
  '/next-7-days': typeof Next7DaysRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/tomorrow': typeof TomorrowRoute
  '/trash': typeof TrashRoute
  '/calendar/month': typeof CalendarMonthRoute
  '/calendar/week': typeof CalendarWeekRoute
  '/project/$id': typeof ProjectIdRouteWithChildren
  '/tag/$name': typeof TagNameRoute
  '/calendar/': typeof CalendarIndexRoute
  '/project/$id/kanban': typeof ProjectIdKanbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/completed'
    | '/inbox'
    | '/next-7-days'
    | '/settings'
    | '/today'
    | '/tomorrow'
    | '/trash'
    | '/calendar/month'
    | '/calendar/week'
    | '/project/$id'
    | '/tag/$name'
    | '/calendar/'
    | '/project/$id/kanban'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all'
    | '/completed'
    | '/inbox'
    | '/next-7-days'
    | '/settings'
    | '/today'
    | '/tomorrow'
    | '/trash'
    | '/calendar/month'
    | '/calendar/week'
    | '/project/$id'
    | '/tag/$name'
    | '/calendar'
    | '/project/$id/kanban'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/completed'
    | '/inbox'
    | '/next-7-days'
    | '/settings'
    | '/today'
    | '/tomorrow'
    | '/trash'
    | '/calendar/month'
    | '/calendar/week'
    | '/project/$id'
    | '/tag/$name'
    | '/calendar/'
    | '/project/$id/kanban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  CompletedRoute: typeof CompletedRoute
  InboxRoute: typeof InboxRoute
  Next7DaysRoute: typeof Next7DaysRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  TomorrowRoute: typeof TomorrowRoute
  TrashRoute: typeof TrashRoute
  CalendarMonthRoute: typeof CalendarMonthRoute
  CalendarWeekRoute: typeof CalendarWeekRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
  TagNameRoute: typeof TagNameRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tomorrow': {
      id: '/tomorrow'
      path: '/tomorrow'
      fullPath: '/tomorrow'
      preLoaderRoute: typeof TomorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-7-days': {
      id: '/next-7-days'
      path: '/next-7-days'
      fullPath: '/next-7-days'
      preLoaderRoute: typeof Next7DaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$name': {
      id: '/tag/$name'
      path: '/tag/$name'
      fullPath: '/tag/$name'
      preLoaderRoute: typeof TagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/week': {
      id: '/calendar/week'
      path: '/calendar/week'
      fullPath: '/calendar/week'
      preLoaderRoute: typeof CalendarWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/month': {
      id: '/calendar/month'
      path: '/calendar/month'
      fullPath: '/calendar/month'
      preLoaderRoute: typeof CalendarMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/kanban': {
      id: '/project/$id/kanban'
      path: '/kanban'
      fullPath: '/project/$id/kanban'
      preLoaderRoute: typeof ProjectIdKanbanRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdKanbanRoute: typeof ProjectIdKanbanRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdKanbanRoute: ProjectIdKanbanRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  CompletedRoute: CompletedRoute,
  InboxRoute: InboxRoute,
  Next7DaysRoute: Next7DaysRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  TomorrowRoute: TomorrowRoute,
  TrashRoute: TrashRoute,
  CalendarMonthRoute: CalendarMonthRoute,
  CalendarWeekRoute: CalendarWeekRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
  TagNameRoute: TagNameRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
